package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"errors"

	"github.com/entegral/officebuddy/types"
	"github.com/entegral/toolbox/dynamo"
)

// PutEngagement is the resolver for the putEngagement field.
func (r *mutationResolver) PutEngagement(ctx context.Context, user types.UserFinder, officeGUID string, eventGUID string) (*types.Engagement, error) {
	trilink, err := dynamo.CheckTriLink[*types.User, *types.Office, *types.Event](
		&user.User,
		&types.Office{GUID: officeGUID},
		&types.Event{GUID: eventGUID},
	)
	if err != nil && !errors.Is(err, dynamo.ErrLinkNotFound{}) {
		return nil, err
	}
	err = trilink.Put(ctx, trilink)
	if err != nil {
		return nil, err
	}
	return &types.Engagement{TriLink: *trilink}, nil
}

// Engagement is the resolver for the engagement field.
func (r *queryResolver) Engagement(ctx context.Context, user types.UserFinder, officeGUID string, eventGUID string) (*types.Engagement, error) {
	trilink, err := dynamo.CheckTriLink[*types.User, *types.Office, *types.Event](
		&user.User,
		&types.Office{GUID: officeGUID},
		&types.Event{GUID: eventGUID},
	)
	if err != nil {
		return nil, err
	}
	err = trilink.Get(ctx, trilink)
	if err != nil {
		return nil, err
	}
	return &types.Engagement{TriLink: *trilink}, nil
}
