package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/entegral/officebuddy/types"
)

// PutEngagement is the resolver for the putEngagement field.
func (r *mutationResolver) PutEngagement(ctx context.Context, user types.UserFinder, officeGUID string, eventGUID string) (*types.Engagement, error) {
	engagement := &types.Engagement{}
	_, err := engagement.CheckLink(ctx, engagement, &user.User, &types.Office{GUID: officeGUID}, &types.Event{GUID: eventGUID})
	if err != nil {
		return nil, err
	}
	return engagement, engagement.Put(ctx, engagement)
}

// Engagement is the resolver for the engagement field.
func (r *queryResolver) Engagement(ctx context.Context, user types.UserFinder, officeGUID string, eventGUID string) (*types.Engagement, error) {
	engagement := &types.Engagement{}
	linkExists, err := engagement.CheckLink(ctx, engagement, &user.User, &types.Office{GUID: officeGUID}, &types.Event{GUID: eventGUID})
	if err != nil {
		return nil, err
	}
	if linkExists {
		return engagement, nil
	}
	return nil, nil
}
