package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/entegral/officebuddy/types"
	"github.com/entegral/toolbox/dynamo"
	"github.com/entegral/toolbox/helpers"
)

// Invites is the resolver for the Invites field.
func (r *eventResolver) Invites(ctx context.Context, obj *types.Event) ([]*types.Invite, error) {
	panic(fmt.Errorf("not implemented: Invites - Invites"))
}

// Venue is the resolver for the Venue field.
func (r *eventResolver) Venue(ctx context.Context, obj *types.Event) ([]*types.Venue, error) {
	panic(fmt.Errorf("not implemented: Venue - Venue"))
}

// PutEvents is the resolver for the putEvents field.
func (r *mutationResolver) PutEvents(ctx context.Context, events []*types.EventInput) ([]*types.Event, error) {
	ret := make([]*types.Event, len(events))
	for i, event := range events {
		_, err := helpers.PutItem(ctx, &event.Event)
		if err != nil {
			return nil, err
		}
		ret[i] = &event.Event
	}
	return ret, nil
}

// DeleteEvent is the resolver for the deleteEvent field.
func (r *mutationResolver) DeleteEvent(ctx context.Context, userEmail string, eventGUID string) (bool, error) {
	event, err := dynamo.CheckDiLink[*types.User, *types.Office](&types.User{Email: userEmail}, &types.Office{GUID: eventGUID})
	switch err.(type) {
	case nil:
		return true, event.Unlink(ctx, event)
	case dynamo.ErrLinkNotFound:
		return false, nil
	default:
		return false, err
	}
}

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

type eventResolver struct{ *Resolver }
