package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/entegral/officebuddy/types"
)

// Office is the resolver for the office field.
func (r *queryResolver) Office(ctx context.Context, officeGUID string) (*types.Office, error) {
	panic(fmt.Errorf("not implemented: Office - office"))
}

// Offices is the resolver for the offices field.
func (r *queryResolver) Offices(ctx context.Context, userGUID string) ([]*types.Office, error) {
	panic(fmt.Errorf("not implemented: Offices - offices"))
}
