package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"time"

	"github.com/entegral/officebuddy/types"
)

// CreatedAt is the resolver for the CreatedAt field.
func (r *membershipResolver) CreatedAt(ctx context.Context, obj *types.Membership) (string, error) {
	return obj.CreatedAt.UTC().Format(time.RFC3339), nil
}

// PutMembership is the resolver for the putMembership field.
func (r *mutationResolver) PutMembership(ctx context.Context, email string, officeGUID string, role types.Role) (*types.Membership, error) {
	membership, err := types.NewMembership(ctx, email, officeGUID, role)
	if err != nil {
		return nil, err
	}
	err = membership.Put(ctx, membership)
	if err != nil {
		return nil, err
	}
	return membership, nil
}

// DeleteMembership is the resolver for the deleteMembership field.
func (r *mutationResolver) DeleteMembership(ctx context.Context, email string, officeGUID string) (bool, error) {
	membership, err := types.NewMembership(ctx, email, officeGUID, types.RoleMember)
	if err != nil {
		return false, err
	}
	err = membership.Delete(ctx, membership)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Membership returns MembershipResolver implementation.
func (r *Resolver) Membership() MembershipResolver { return &membershipResolver{r} }

type membershipResolver struct{ *Resolver }
