package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/entegral/officebuddy/types"
)

// PutOffice is the resolver for the putOffice field.
func (r *mutationResolver) PutOffice(ctx context.Context, guid *string, name string, createdByEmail string, address types.AddressInput, description *string) (*types.Office, error) {
	office := types.NewOffice(ctx, name, createdByEmail, guid, description, address.Address)
	return &office, office.Put(ctx, &office)
}

// DeleteOffice is the resolver for the deleteOffice field.
func (r *mutationResolver) DeleteOffice(ctx context.Context, officeGUID string) (*types.Office, error) {
	office := types.Office{
		GUID: officeGUID,
	}
	err := office.Delete(ctx, &office)
	if err != nil {
		return nil, err
	}
	return &office, nil
}

// Office is the resolver for the office field.
func (r *queryResolver) Office(ctx context.Context, officeGUID string) (*types.Office, error) {
	office := types.Office{
		GUID: officeGUID,
	}
	err := office.Get(ctx, &office)
	if err != nil {
		return nil, err
	}
	if office.GetItemOutput == nil || office.GetItemOutput.Item == nil {
		return nil, nil
	}
	return &office, nil
}
