package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/entegral/officebuddy/types"
)

// PutVenue is the resolver for the putVenue field.
func (r *mutationResolver) PutVenue(ctx context.Context, officeGUID string, eventGUID string, room *string, instructions *string) (*types.Venue, error) {
	venue, err := types.NewVenue(ctx, types.Event{GUID: eventGUID}, types.Office{GUID: officeGUID}, &types.NewVenueOpts{Room: room, Instructions: instructions})
	if err != nil {
		return nil, err
	}
	err = venue.Put(ctx, venue)
	if err != nil {
		return nil, err
	}
	return venue, nil
}
